name: Run Shared Build and Push Workflow

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'sql/migrations/*'
      - 'sql/data/**/*'
      - 'Dockerfile'
      - '.dockerignore'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        database:
          - postgres

    permissions:
      contents: read
      packages: write # required if push is true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Building ${{ matrix.database }} image
        uses: jabez007/aws-kubectl/.github/shared/docker@master
        with:
          context: ./sql/${{ matrix.database }}
          tag: ${{ matrix.database }}
          push: true
          debug: ${{ vars.pipeline_debug }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}